name: flutter_advanced_networkimage_2
description: An advanced image provider provides caching and retrying for flutter app. Now with zoomable widget and transition to image widget.
version: 2.0.1
repository: https://github.com/bgpworks/flutter_advanced_networkimage

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  path_provider: ^2.0.8
  path: ^1.8.3
  pool: ^1.5.1
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: "^1.9.0"
